version: "3"

services:

  postgres:
    container_name: postgres_db
    image: postgres:12
    ports:
        - 5432:5432
    volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/0001-init.sql
        - ./db_data/data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_HOST=${POSTGRES_HOST}

  
  api:
    container_name: api_app
    build: ./api
    ports:
        - 4300:4300
    restart: on-failure
    depends_on:
        - postgres
    environment:
      - POSTGRES_DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_HOST}/${POSTGRES_DB} # 'postgres://<user>:<pass>@<host>>:<port>>/<dbname>'

volumes:
    db_data:

networks:
    backend:
        driver: bridge